CC = gcc
TARGET_ASIAKAS = asiakas
TARGET_PALVELIN = palvelin
SRC_ASIAKAS = asiakas.c
SRC_PALVELIN = palvelin.c

all: $(TARGET_ASIAKAS) $(TARGET_PALVELIN)

$(TARGET_ASIAKAS): $(SRC_ASIAKAS)
	$(CC) -o $(TARGET_ASIAKAS) $(SRC_ASIAKAS)

$(TARGET_PALVELIN): $(SRC_PALVELIN)
	$(CC) -o $(TARGET_PALVELIN) $(SRC_PALVELIN)

clean:
	rm -f $(TARGET_ASIAKAS) $(TARGET_PALVELIN)
